[TASK-408] Create entity
Speechpeach/speech-backend pull request #14
Opened 2024-04-25 08:44 UTC by beautiflow

## Description
 [Task-408](https://www.notion.so/ba581e91f34048149c0fd3de53cec59d?pvs=4)
- [x]  메모 엔티티 생성
- [x]  멘토 엔티티 생성
- [x]  멘토 경력사항 엔티티 생성
- [x]  경력 링크 엔티티 생성
- [x]  멘토링 가능날짜 엔티티 생성

## 결과
<img src="https://github.com/Speechpeach/speech-backend/assets/105831341/25be2eab-668f-4929-9ecb-75b04495f68f.png" width="300" height="200" />

## More
members 테이블은 기존 User 테이블 이름을 로컬에서 변경한 것입니다.

2024-04-25 19:07 UTC, blacklabf commented on src/main/java/com/speechpeach/speech/memo/entity/Memo.java
> +    private Member memberId;
Member 객체를 가져오기 때문에 변수명을 memberId 보다는 member로 하면 좋을 거 같습니다! 
예시로  memo에서 join된 member 엔티티의 속성을 가져다 쓸 경우 저 변수명으로 조회하기 때문에 member로 하면 좀 더 직관적으로 보일 수 있을 거 같습니다!

2024-04-25 19:07 UTC, blacklabf commented on src/main/java/com/speechpeach/speech/memo/entity/Memo.java
> +    private YoutubeVideo youtubeVideoId;
위와 같은 이유로 youtubeVideo로 변경하시면 좋을 거 같습니다!

2024-04-25 19:08 UTC, blacklabf commented on src/main/java/com/speechpeach/speech/mento/entity/CareerLink.java
> +    private Mento mentoId;
여기도 수정 부탁드립니다!

2024-04-25 19:10 UTC, blacklabf commented on src/main/java/com/speechpeach/speech/memo/entity/Memo.java
> +@NoArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)으로 기본 생성자의 접근 수준을 protected로 지정하면 클래스의 직접적인 사용을 제한하고 보다 통제된 방식으로 확장을 허용할 때 유용할 거 같습니다! 😃

2024-04-25 19:18 UTC, blacklabf commented on src/main/java/com/speechpeach/speech/mento/entity/CareerLink.java
> +@Builder
class 레벨에서 Builder 패턴을 생성하면, 모든 필드에 대해 setter 메소드를 제공하는 걸로 알고 있습니다! 
그럴 경우, 객체의 상태를 언제든 변화시킬 수 있어서 멀티스레드 환경에서 객체의 불변성을 보장하기 어려울 거 같습니다! 
생성자 레벨에서 Builder 패턴을 생성하면 더 좋을 거 같습니다! 
혹시 제가 잘 못 알고 있다면 정정부탁드립니다!

2024-04-25 19:20 UTC, blacklabf commented on src/main/java/com/speechpeach/speech/memo/entity/Memo.java
> +    @Column(name = "memo_content", nullable = false)
따로 타입 지정없이 String으로 하면 varchar(255)로 세팅되어서 column타입을 text로 지정해두어야할 것 같습니다! ex) @Column(columnDefinition = "TEXT", nullable = false)

2024-04-25 19:22 UTC, blacklabf commented on src/main/java/com/speechpeach/speech/mento/entity/MentoringPossibleDate.java
> +    @Column(name = "mentoring_possible_date_day", nullable = false)
여기도 따로 타입 지정없이 String으로 하면 varchar(255)로 세팅되어서 저희 ERD 구성한대로 varchar의 크기를 명시해줘야 할 거 같습니다!

2024-04-25 19:23 UTC, blacklabf commented
코드리뷰 남겼습니다!

2024-04-26 01:44 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/memo/entity/Memo.java
> +    private Member memberId;
네 알겠습니다!

2024-04-26 01:45 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/memo/entity/Memo.java
> +    private YoutubeVideo youtubeVideoId;
네!!

2024-04-26 01:45 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mento/entity/CareerLink.java
> +    private Mento mentoId;
네!!

2024-04-26 01:45 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/memo/entity/Memo.java
> +@NoArgsConstructor
네 알겠습니당!

2024-04-26 01:46 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mento/entity/CareerLink.java
> +@Builder
네 감사합니다!!

2024-04-26 01:46 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/memo/entity/Memo.java
> +    @Column(name = "memo_content", nullable = false)
네 알겠습니당!

2024-04-26 01:46 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mento/entity/MentoringPossibleDate.java
> +    @Column(name = "mentoring_possible_date_day", nullable = false)
네 확인했습니다!!

2024-04-26 02:36 UTC, beautiflow commented
변경했습니다!

2024-04-28 23:38 UTC, Kim-AYoung requested changes

2024-04-28 23:38 UTC, Kim-AYoung commented on src/main/java/com/speechpeach/speech/mentoring/entity/Mentor.java
> +    private String mentorCareerPeriod;
➕ 해당 필드가 가질수 있는 값이 한정적이므로 필드타입이 Enum으로 변경되면 좋을 것 같습니다!
Enum 클래스에 들어갈 값들은 추후 논의로 정하면 될 것 같습니다.

2024-04-28 23:38 UTC, Kim-AYoung commented on src/main/java/com/speechpeach/speech/mentoring/entity/Mentor.java
> +    private String mentorGenre;
➕ 해당 필드도 Enum으로 지정되면 좋을 것 같습니다!
Enum 클래스에 들어갈 값들은 추후 논의로 정하면 될 것 같습니다.

2024-04-28 23:38 UTC, Kim-AYoung commented on src/main/java/com/speechpeach/speech/mentoring/entity/Mentor.java
> +    private String mentorStatusId;
➕ 해당 필드도 Enum으로 지정되면 좋을 것 같습니다!
Enum 클래스에 들어갈 값은 ENABLED, DISABLED 두가지일 것 같습니다!

2024-04-28 23:38 UTC, Kim-AYoung commented on src/main/java/com/speechpeach/speech/mentoring/entity/MentoringApplication.java
> +    private String mentoringApplyStatus;
➕ 해당 필드도 Enum으로 지정되면 좋을 것 같습니다!
Enum 클래스에 들어갈 값들은 이전에 기획한대로 '승인대기, 결제대기, 예약 확정, 이용완료, 취소_환불'의 영문명이 될 것 같습니다.

2024-04-28 23:38 UTC, Kim-AYoung commented on src/main/java/com/speechpeach/speech/mentoring/entity/MentoringPossibleDate.java
> +    private String mentoringPossibleDateDay;
➕ 해당 필드도 Enum으로 지정되면 좋을 것 같습니다!
Enum 클래스에 들어갈 값들은 'MON ~ SUN'이 될 것 같습니다.

2024-04-28 23:38 UTC, Kim-AYoung commented on src/main/java/com/speechpeach/speech/mentoring/entity/Review.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
⚠ `Review` 테이블 식별자의 값으로 `MentoringApplication` 테이블의 식별자 값을 가지므로, 식별자 값 자동생성부분이 제거되어야할 것 같습니다!

2024-04-29 04:06 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mentoring/entity/Mentor.java
> +    private String mentorCareerPeriod;
네 알겠습니다!

2024-04-29 04:06 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mentoring/entity/Mentor.java
> +    private String mentorGenre;
네! 반영하겠습니다!

2024-04-29 04:06 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mentoring/entity/Mentor.java
> +    private String mentorStatusId;
넵!

2024-04-29 04:06 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mentoring/entity/MentoringApplication.java
> +    private String mentoringApplyStatus;
네! 알겠습니다!

2024-04-29 04:06 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mentoring/entity/MentoringPossibleDate.java
> +    private String mentoringPossibleDateDay;
넵 반영하겠습니당

2024-04-29 04:07 UTC, beautiflow commented on src/main/java/com/speechpeach/speech/mentoring/entity/Review.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
아하 넵!!

2024-04-29 06:00 UTC, Kim-AYoung approved these changes
👍 LGTM

2024-04-30 08:11 UTC, blacklabf commented
Good Code 😄

2024-04-30 08:16 UTC, blacklabf approved these changes

2024-04-30 15:15 UTC, merged